{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slumcast.serviceAccountName" . }}
  labels:
{{ include "slumcast.labels" . | nindent 4 }}
{{- end -}}
