import {
    WEBSOCKET_BROKEN,
    WEBSOCKET_CLOSED,
    WEBSOCKET_CONNECT,
    WEBSOCKET_DISCONNECT,
    WEBSOCKET_MESSAGE,
    WEBSOCKET_OPEN,
    WEBSOCKET_SEND,
  } from '@giantmachines/redux-websocket';

export const REDUX_WEBSOCKET_BROKEN = `REDUX_WEBSOCKET::${WEBSOCKET_BROKEN}`
export const REDUX_WEBSOCKET_CLOSED = `REDUX_WEBSOCKET::${WEBSOCKET_CLOSED}`
export const REDUX_WEBSOCKET_MESSAGE = `REDUX_WEBSOCKET::${WEBSOCKET_MESSAGE}`
export const REDUX_WEBSOCKET_OPEN = `REDUX_WEBSOCKET::${WEBSOCKET_OPEN}`
export const REDUX_WEBSOCKET_DISCONNECT = `REDUX_WEBSOCKET::${WEBSOCKET_DISCONNECT}`
export const REDUX_WEBSOCKET_CONNECT = `REDUX_WEBSOCKET::${WEBSOCKET_CONNECT}`
export const REDUX_WEBSOCKET_SEND = `REDUX_WEBSOCKET::${WEBSOCKET_SEND}`
