name: "CI"
# SECRETS NEEDED:
# DOCKER_USERNAME - Container Registry Username (github or dockerhub)
# DOCKER_ACCESS_TOKEN - Container registry Personal access token with push priveledges
# HELM_CHARTS_PAT - PAT that has access to push to the github based helm charts repo such eg: https://github.com/bsord/helm-charts

on:
  push:
    branches:
      - "master"
      - "main"
      - "develop"

jobs:
  helm-lint:
    name: Lint Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Helm chart
        run: helm lint ./chart

  docker-build:
    name: Docker Build
    needs: [helm-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ steps.vars.outputs.sha_short }}
          restore-keys: |
            ${{ runner.os }}-buildx-
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - name: Build & Push Base Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  chart-test:
    name: Validate Helm chart
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Update chart image tag
        run: |
          sed -r -i 's/(appVersion:[^*])([[:alnum:].]*.*)/\1${{ steps.vars.outputs.sha_short }}/g' ./chart/Chart.yaml

      - name: Create Kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Install and Test chart
        id: test-chart
        run: |
          helm install test-release ./chart --wait --debug
          helm test test-release

      - name: Debug Helm Chart
        if: failure() && steps.test-chart.outcome == 'failure'
        run: |
          kubectl get events
          kubectl describe hpa
          kubectl describe deploy
          kubectl describe ing
          kubectl describe pdb
          kubectl describe svc
          kubectl describe serviceaccount
          kubectl describe po

          for pod in `kubectl get po -o json |  jq '.items[] | .metadata.name' | sed 's/"//g'` ; do
            echo $pod
            kubectl logs $pod 
          done

  release:
    name: "Release"
    needs: [chart-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: Get next version
        id: get-next-version
        uses: bsord/conventional-changelog-action@v3.7.0
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: ''
          skip-version-file: true
          dry-run: true

      - name: Update version in version files
        if: ${{ steps.get-next-version.outputs.skipped == 'false' }}
        run: |
          sed -r -i 's/(\"version\":[^*]\")([[:alnum:].]*)/\1${{ steps.get-next-version.outputs.version }}/g' package.json
          sed -r -i 's/(version:[^*]|appVersion:[^*])([[:alnum:].]*)/\1${{ steps.get-next-version.outputs.version }}/g' ./chart/Chart.yaml
      - name: Commit changes
        if: ${{ steps.get-next-version.outputs.skipped == 'false' }}
        uses: EndBug/add-and-commit@v5
        with:
          message: "chore(version): Bump to: ${{ steps.get-next-version.outputs.version }}"
          tag: "${{ steps.get-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog and tag with new version
        if: ${{ steps.get-next-version.outputs.skipped == 'false' }}
        uses: bsord/conventional-changelog-action@v3.7.0
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: ''
          skip-version-file: true
      
      - name: Create Release
        if: ${{ steps.get-next-version.outputs.skipped == 'false' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.get-next-version.outputs.version }}
          release_name: ${{ steps.get-next-version.outputs.version }}
          body: ${{ steps.get-next-version.outputs.clean_changelog }}

      - name: Build and publish Docker image
        if: ${{ steps.get-next-version.outputs.skipped == 'false' }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          tags: "latest,${{ steps.get-next-version.outputs.version }}"

      - name: Push Helm chart
        if: ${{ steps.get-next-version.outputs.skipped == 'false' }}
        uses: bsord/helm-push@v3
        with:
          access-token: ${{ secrets.CM_API_KEY }}
          repository-url: ${{ secrets.CM_REPO_URL }} 
          force: true
          chart-folder: chart